http:
  port: 8080
admin:
  port: 9876
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  auth:
    host: localhost
    paths: ['/auth', '/auth/*']
  user:
    host: localhost
    paths: ['/user', '/user/*']
  match:
    host: localhost
    paths: ['/match', '/match/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  authService:
    url: 'http://localhost:3002'
  userService:
    url: 'http://localhost:3003'
  matchService:
    url: 'http://localhost:3004' 
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit  
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action: 
              serviceEndpoint: authService
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  matchPipeline:
    apiEndpoints:
      - match
    policies:
      - proxy:
          - action:
              serviceEndpoint: matchService
              changeOrigin: true

